include $(TOPDIR)/rules.mk

LUCI_TITLE:=PPE hardware QoS configuration
LUCI_DEPENDS:=+ppe-qos
LUCI_PKGARCH:=all
PKG_LICENSE:=GPL-2.0-only

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
